"""0001 initial

Revision ID: 8b525ba1f866
Revises: 
Create Date: 2026-10-03 12:38:27.234417
"""
from alembic import op
import sqlalchemy as sa


revision = '8b525ba1f866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('camera_health',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('ai_status', sa.String(length=16), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('frame_drops', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('last_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_health_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_camera_health_camera_ts', ['camera_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_health_ts'), ['ts'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('track_ids', sa.JSON(), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=True),
    sa.Column('zone_name', sa.String(length=128), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=128), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_event_camera_timestamp', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_event_dedup', ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_event_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)

    op.create_table('model',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('commercial_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_name'), ['name'], unique=True)

    op.create_table('organization',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_profile',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_profile_name'), ['name'], unique=True)

    op.create_table('alert',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index('ix_alert_event_channel', ['event_id', 'channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_event_id'), ['event_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_event_id'), ['event_id'], unique=False)
        batch_op.create_index('ix_evidence_expires', ['expires_at'], unique=False)

    op.create_table('model_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('training_data', sa.JSON(), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_version_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_model_version_unique', ['model_id', 'version'], unique=True)

    op.create_table('site',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_org_id'), ['org_id'], unique=False)

    op.create_table('track',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('external_track_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('trajectory', sa.JSON(), nullable=False),
    sa.Column('current_zone', sa.String(length=128), nullable=True),
    sa.Column('previous_zones', sa.JSON(), nullable=False),
    sa.Column('dwell_seconds', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_track_camera_track', ['camera_id', 'external_track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_event_id'), ['event_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_org_id'), ['org_id'], unique=False)

    op.create_table('camera',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('detection_fps', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('retention', sa.JSON(), nullable=False),
    sa.Column('model_profile', sa.String(length=64), nullable=False),
    sa.Column('rule_profile', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_camera_id'), ['camera_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_camera_site_id'), ['site_id'], unique=False)

    op.create_table('deployment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_model_version_id'), ['model_version_id'], unique=False)

    op.create_table('rule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('camera_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('zone_ids', sa.JSON(), nullable=False),
    sa.Column('line', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('cooldown_seconds', sa.Float(), nullable=False),
    sa.Column('confirm_seconds', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['rule_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_rule_key'), ['rule_key'], unique=False)

    op.create_table('zone',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_zone_camera_name', ['camera_id', 'name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_index('ix_zone_camera_name')
        batch_op.drop_index(batch_op.f('ix_zone_camera_id'))

    op.drop_table('zone')
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_rule_key'))
        batch_op.drop_index(batch_op.f('ix_rule_camera_id'))

    op.drop_table('rule')
    with op.batch_alter_table('deployment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_model_version_id'))

    op.drop_table('deployment')
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_site_id'))
        batch_op.drop_index(batch_op.f('ix_camera_camera_id'))

    op.drop_table('camera')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_org_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_api_key_hash'))

    op.drop_table('user')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_event_id'))
        batch_op.drop_index('ix_track_camera_track')
        batch_op.drop_index(batch_op.f('ix_track_camera_id'))

    op.drop_table('track')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_org_id'))

    op.drop_table('site')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index('ix_model_version_unique')
        batch_op.drop_index(batch_op.f('ix_model_version_model_id'))

    op.drop_table('model_version')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_expires')
        batch_op.drop_index(batch_op.f('ix_evidence_event_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_camera_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_event_id'))
        batch_op.drop_index('ix_alert_event_channel')

    op.drop_table('alert')
    with op.batch_alter_table('rule_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_profile_name'))

    op.drop_table('rule_profile')
    op.drop_table('role')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_name'))

    op.drop_table('model')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))
        batch_op.drop_index('ix_event_status_severity')
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index('ix_event_dedup')
        batch_op.drop_index('ix_event_camera_timestamp')
        batch_op.drop_index(batch_op.f('ix_event_camera_id'))

    op.drop_table('event')
    with op.batch_alter_table('camera_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_health_ts'))
        batch_op.drop_index('ix_camera_health_camera_ts')
        batch_op.drop_index(batch_op.f('ix_camera_health_camera_id'))

    op.drop_table('camera_health')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
