"""0002 event summary

Revision ID: dcfc0d2a87b2
Revises: 8b525ba1f866
Create Date: 2026-10-03 16:57:17.852097
"""
from alembic import op
import sqlalchemy as sa


revision = 'dcfc0d2a87b2'
down_revision = '8b525ba1f866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
